apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "5000"
  CLIENT_URL: "http://mern-service:5173"
  NODE_ENV: "development"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb-service:27017/"
  UPSTASH_REDIS_URL: "redis://redis-service:6379"
  ACCESS_TOKEN_SECRET: "your_access_token_secret"
  REFRESH_TOKEN_SECRET: "your_refresh_token_secret"
  CLOUDINARY_CLOUD_NAME: "your_cloud_name"
  CLOUDINARY_API_KEY: "your_cloudinary_api_key"
  CLOUDINARY_API_SECRET: "your_cloudinary_api_secret"
  STRIPE_SECRET_KEY: "your_stripe_secret_key"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mern-backend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000