name: Test CI/CD

on:
  push:
    branches:
    - main
    - Sep-9
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello
        run: Hello World

